# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PPTurl' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PPTurl
  pod 'Alamofire' 
  pod 'FeedKit'
  pod 'SDWebImage', '~> 5.0'
  pod 'SVProgressHUD'

end
